CREATE DATABASE M_SSolve;
USE M_SSolve;
CREATE TABLE Clientes
(
	IdCliente INT IDENTITY PRIMARY KEY
	, Nome VARCHAR(255) NOT NULL
	, RazaoSocial VARCHAR(255) NOT NULL
	, Endereco VARCHAR(255) NOT NULL
	, CNPJ VARCHAR(255) NOT NULL
);
CREATE TABLE Funcionarios
(
	IdFuncionario INT IDENTITY PRIMARY KEY
	, Nome VARCHAR(255) NOT NULL
	, Salario VARCHAR(255) NOT NULL
);
CREATE TABLE Servicos
(
	IdServico INT IDENTITY PRIMARY KEY
	, IdCliente INT FOREIGN KEY REFERENCES Clientes(IdCliente)
	, Comodo VARCHAR(255) NOT NULL
	, Descricao VARCHAR(255) NOT NULL
	, Preco VARCHAR(255) NOT NULL
);
CREATE TABLE FuncionarioServico
(
	IdServico INT IDENTITY PRIMARY KEY
	, IdFuncionario INT FOREIGN KEY REFERENCES Funcionarios(IdFuncionario)
);
